"""Termos e siglas explicados nas caixinhas clicáveis do texto das aulas.

Curado a partir do vocabulário real usado nas 60 aulas da trilha (Onda 3).
`term` precisa bater exatamente com a grafia usada no texto (sensível a
maiúsculas/minúsculas) — é assim que `annotate_glossary_terms` encontra a
primeira ocorrência de cada termo para marcar.

Adicionar um termo novo aqui e rodar `manage.py seed_glossary` é o caminho
padrão. Editar pelo admin também funciona e passa a proteger aquele termo
específico do próximo seed (mesmo `seed_managed` usado em Lesson/Question).
"""
from __future__ import annotations

GLOSSARY_TERMS: list[dict[str, str]] = [
    # --- Redes ---
    {"term": "DNS", "definition": "Sistema que traduz nome de domínio (ex.: exemplo.com) em endereço IP."},
    {"term": "TCP", "definition": "Protocolo de transporte com garantia de entrega e ordem dos dados, usado por HTTP, SSH, etc."},
    {"term": "UDP", "definition": "Protocolo de transporte sem garantia de entrega, mais rápido que TCP; usado em DNS, streaming, jogos."},
    {"term": "HTTP", "definition": "Protocolo de comunicação da web, sem criptografia — tudo trafega em texto puro."},
    {"term": "HTTPS", "definition": "HTTP rodando sobre TLS: o conteúdo trafega criptografado entre cliente e servidor."},
    {"term": "SSH", "definition": "Protocolo para acesso remoto seguro a um servidor via linha de comando, com autenticação criptográfica."},
    {"term": "VPN", "definition": "Rede virtual privada: cria um túnel criptografado entre dois pontos sobre uma rede pública."},
    {"term": "CIDR", "definition": "Notação que descreve uma faixa de IPs (ex.: 10.0.0.0/16), o número após a barra indica o tamanho da faixa."},
    {"term": "NAT", "definition": "Tradução de endereço de rede: permite que máquinas privadas saiam para a internet compartilhando um IP público."},
    {"term": "CDN", "definition": "Rede de servidores distribuídos geograficamente que entrega conteúdo a partir do ponto mais próximo do usuário."},
    {"term": "mTLS", "definition": "TLS mútuo: cliente e servidor verificam a identidade um do outro, não só o cliente verificando o servidor."},
    {"term": "QUIC", "definition": "Protocolo de transporte moderno sobre UDP, base do HTTP/3, com handshake mais rápido que TCP+TLS tradicional."},
    # --- Identidade e acesso ---
    {"term": "IAM", "definition": "Identity and Access Management: sistema de identidade, permissão e política de acesso de uma nuvem."},
    {"term": "MFA", "definition": "Autenticação multifator: exige mais de um fator (senha + código, senha + hardware key) para provar identidade."},
    {"term": "SSO", "definition": "Single Sign-On: um único login dá acesso a vários sistemas, sem precisar autenticar de novo em cada um."},
    {"term": "OIDC", "definition": "OpenID Connect: protocolo de identidade sobre OAuth 2.0, usado por CI/CD para trocar identidade por credencial temporária."},
    {"term": "SAML", "definition": "Protocolo de federação de identidade baseado em XML, comum em SSO corporativo mais antigo."},
    {"term": "JWT", "definition": "JSON Web Token: token assinado que carrega dado de identidade verificável sem precisar consultar um banco a cada request."},
    {"term": "RBAC", "definition": "Controle de acesso baseado em papel (role): permissão é atribuída ao papel, e o usuário herda a permissão do papel que ocupa."},
    {"term": "ABAC", "definition": "Controle de acesso baseado em atributo (tag): a regra compara atributo do usuário com atributo do recurso, sem role fixo."},
    {"term": "STS", "definition": "Security Token Service: serviço que emite credencial temporária de curta duração, base do AssumeRole na AWS."},
    {"term": "SCP", "definition": "Service Control Policy: guard-rail aplicado a uma conta ou organização inteira na AWS, que nem o admin local pode contornar."},
    {"term": "SSM", "definition": "AWS Systems Manager: entre outras coisas, permite sessão remota num servidor sem abrir porta SSH."},
    {"term": "PII", "definition": "Personally Identifiable Information: qualquer dado que identifica uma pessoa (CPF, e-mail, nome completo)."},
    # --- Criptografia e segredos ---
    {"term": "TLS", "definition": "Transport Layer Security: protocolo que criptografa a comunicação de rede, sucessor do SSL."},
    {"term": "SSL", "definition": "Antecessor do TLS; hoje considerado inseguro e desabilitado em qualquer configuração moderna."},
    {"term": "PKI", "definition": "Infraestrutura de chave pública: o conjunto de certificado, chave e autoridade que sustenta HTTPS e assinatura digital."},
    {"term": "CA", "definition": "Autoridade Certificadora: entidade que assina certificado digital, atestando que uma chave pública pertence a quem diz ser."},
    {"term": "HSM", "definition": "Hardware Security Module: chip dedicado que guarda chave criptográfica sem nunca deixá-la sair em texto puro."},
    {"term": "KMS", "definition": "Key Management Service: serviço gerenciado de chave criptográfica na nuvem, apoiado por HSM."},
    {"term": "CMK", "definition": "Customer Managed Key: chave no KMS criada e controlada pelo próprio cliente, não pela nuvem."},
    {"term": "HSTS", "definition": "Header que instrui o navegador a usar HTTPS sempre, sem tentar HTTP primeiro, mesmo na primeira visita."},
    # --- Vulnerabilidades e testes de segurança ---
    {"term": "RCE", "definition": "Remote Code Execution: falha que permite a um atacante rodar código arbitrário num sistema remoto."},
    {"term": "XSS", "definition": "Cross-Site Scripting: falha que permite injetar script malicioso numa página vista por outro usuário."},
    {"term": "SSRF", "definition": "Server-Side Request Forgery: falha que faz o próprio servidor fazer uma requisição para onde o atacante quer, não o atacante direto."},
    {"term": "SQLi", "definition": "SQL Injection: falha que permite inserir comando SQL malicioso através de um campo de input não validado."},
    {"term": "CVE", "definition": "Common Vulnerabilities and Exposures: identificador único e público para uma vulnerabilidade conhecida."},
    {"term": "CVSS", "definition": "Common Vulnerability Scoring System: nota de 0 a 10 que mede a severidade técnica de uma CVE."},
    {"term": "EPSS", "definition": "Exploit Prediction Scoring System: estima a probabilidade real de uma CVE ser explorada nos próximos 30 dias."},
    {"term": "KEV", "definition": "Known Exploited Vulnerabilities: catálogo da CISA de CVEs que já foram exploradas em ataque real."},
    {"term": "SAST", "definition": "Static Application Security Testing: analisa o código-fonte em busca de vulnerabilidade sem executá-lo."},
    {"term": "DAST", "definition": "Dynamic Application Security Testing: ataca a aplicação já rodando, como um atacante real faria pela rede."},
    {"term": "SCA", "definition": "Software Composition Analysis: mapeia as dependências de um projeto e cruza com bases de CVE conhecidas."},
    {"term": "WAF", "definition": "Web Application Firewall: filtro que inspeciona requisição HTTP e bloqueia padrão de ataque conhecido (SQLi, XSS)."},
    {"term": "OWASP", "definition": "Open Worldwide Application Security Project: organização sem fins lucrativos referência em segurança de aplicação web."},
    {"term": "SIEM", "definition": "Security Information and Event Management: centraliza log de segurança de vários sistemas para correlação e alerta."},
    {"term": "EDR", "definition": "Endpoint Detection and Response: monitora comportamento num host individual (laptop, servidor) em busca de atividade maliciosa."},
    {"term": "IDS", "definition": "Intrusion Detection System: monitora tráfego de rede e alerta sobre padrão suspeito, sem bloquear."},
    {"term": "IPS", "definition": "Intrusion Prevention System: como o IDS, mas bloqueia ativamente o tráfego suspeito detectado."},
    {"term": "MITRE", "definition": "Organização sem fins lucrativos que mantém bases de referência em segurança, como o catálogo CVE e o framework ATT&CK."},
    {"term": "ATT&CK", "definition": "Framework do MITRE que cataloga tática e técnica real usada por atacante, organizado por fase do ataque."},
    {"term": "NIST", "definition": "National Institute of Standards and Technology: agência dos EUA que publica padrão técnico, incluindo os de criptografia."},
    {"term": "CIS", "definition": "Center for Internet Security: publica os CIS Benchmarks, guias de configuração segura para sistema e nuvem."},
    {"term": "LGPD", "definition": "Lei Geral de Proteção de Dados: legislação brasileira que regula como empresas coletam e tratam dado pessoal."},
    {"term": "GDPR", "definition": "General Data Protection Regulation: a lei de proteção de dados da União Europeia, referência que inspirou a LGPD."},
    {"term": "HIPAA", "definition": "Lei dos EUA que regula proteção de dado de saúde; exige controle específico de qualquer sistema que lide com isso."},
    {"term": "PCI", "definition": "PCI DSS: padrão de segurança exigido de qualquer sistema que processa dado de cartão de crédito."},
    {"term": "SOC 2", "definition": "Auditoria de controle de segurança amplamente exigida de fornecedor de software como prova de maturidade operacional."},
    # --- Supply chain / SBOM ---
    {"term": "SBOM", "definition": "Software Bill of Materials: lista completa de dependências (diretas e indiretas) de um software, com versão."},
    {"term": "SPDX", "definition": "Formato de SBOM mantido pela Linux Foundation, com foco em compliance e licenciamento."},
    {"term": "OSV", "definition": "Open Source Vulnerabilities: base de dados aberta de vulnerabilidade em pacote open source, mantida pelo Google."},
    {"term": "SLSA", "definition": "Supply chain Levels for Software Artifacts: framework com níveis crescentes de garantia sobre como um artefato foi construído."},
    {"term": "VEX", "definition": "Vulnerability Exploitability eXchange: documento que declara se uma CVE presente numa dependência é de fato explorável naquele uso."},
    {"term": "CNCF", "definition": "Cloud Native Computing Foundation: organização que hospeda projetos open source de referência em nuvem nativa (Kubernetes, Prometheus)."},
    {"term": "OCI", "definition": "Open Container Initiative: padrão aberto que define o formato de imagem de container e de registry."},
    # --- Cloud / infraestrutura ---
    {"term": "AWS", "definition": "Amazon Web Services, a maior provedora de nuvem pública do mercado."},
    {"term": "GCP", "definition": "Google Cloud Platform, a nuvem pública do Google."},
    {"term": "VPC", "definition": "Virtual Private Cloud: uma rede privada isolada dentro de uma nuvem pública."},
    {"term": "SG", "definition": "Security Group: firewall stateful aplicado a uma instância ou interface de rede na AWS."},
    {"term": "NACL", "definition": "Network ACL: firewall stateless aplicado a uma subnet inteira na AWS."},
    {"term": "AZ", "definition": "Availability Zone: datacenter isolado dentro de uma região de nuvem, com energia e rede independentes dos demais."},
    {"term": "S3", "definition": "Simple Storage Service: o serviço de armazenamento de objeto da AWS."},
    {"term": "EC2", "definition": "Elastic Compute Cloud: o serviço de máquina virtual da AWS."},
    {"term": "RDS", "definition": "Relational Database Service: banco de dados relacional gerenciado pela AWS."},
    {"term": "EKS", "definition": "Elastic Kubernetes Service: Kubernetes gerenciado pela AWS."},
    {"term": "ECR", "definition": "Elastic Container Registry: o registry de imagem de container da AWS."},
    {"term": "GHCR", "definition": "GitHub Container Registry: registry de imagem de container integrado ao GitHub."},
    {"term": "SLA", "definition": "Service Level Agreement: compromisso contratual de disponibilidade ou performance de um serviço."},
    {"term": "SLO", "definition": "Service Level Objective: a meta interna de confiabilidade que sustenta o SLA prometido ao cliente."},
    {"term": "SLI", "definition": "Service Level Indicator: a métrica real medida (latência, taxa de erro) usada para avaliar se o SLO está sendo cumprido."},
    {"term": "RTO", "definition": "Recovery Time Objective: em quanto tempo um serviço precisa voltar depois de um incidente."},
    {"term": "RPO", "definition": "Recovery Point Objective: quanto de dado é aceitável perder num incidente, medido em tempo desde o último backup."},
    {"term": "MTTR", "definition": "Mean Time To Restore: tempo médio para recuperar de um incidente."},
    {"term": "DORA", "definition": "Pesquisa do Google que define 4 métricas de performance de engenharia: frequência de deploy, lead time, MTTR e taxa de falha."},
    {"term": "HA", "definition": "High Availability: arquitetura desenhada para continuar funcionando mesmo com a falha de um componente."},
    {"term": "WORM", "definition": "Write Once, Read Many: modelo de armazenamento onde o dado, uma vez escrito, não pode ser alterado nem apagado por um prazo."},
    {"term": "PID", "definition": "Process ID: identificador único de um processo em execução no sistema operacional."},
    {"term": "UID", "definition": "User ID: identificador numérico de um usuário no sistema operacional; UID 0 é sempre o root."},
    {"term": "GIL", "definition": "Global Interpreter Lock: trava do interpretador Python que impede duas threads rodarem bytecode Python ao mesmo tempo."},
    {"term": "UFW", "definition": "Uncomplicated Firewall: interface simplificada para configurar firewall no Linux, por cima do netfilter."},
    # --- CI/CD e desenvolvimento ---
    {"term": "CI", "definition": "Continuous Integration: a cada commit, o código é validado automaticamente (build, lint, teste)."},
    {"term": "CD", "definition": "Continuous Delivery/Deployment: o código validado fica sempre pronto para produção, com ou sem aprovação manual final."},
    {"term": "PR", "definition": "Pull Request: proposta de mudança de código, revisada antes de ser integrada ao branch principal."},
    {"term": "IaC", "definition": "Infrastructure as Code: infraestrutura descrita em arquivo versionado, em vez de configurada manualmente."},
    {"term": "CLI", "definition": "Command Line Interface: forma de interagir com um programa via linha de comando, em vez de interface gráfica."},
    {"term": "API", "definition": "Application Programming Interface: contrato que permite um sistema conversar com outro."},
    {"term": "REST", "definition": "Estilo de arquitetura de API baseado em recurso e verbo HTTP (GET, POST, PUT, DELETE)."},
    {"term": "JSON", "definition": "Formato de texto leve para troca de dado estruturado, o mais comum em API web hoje."},
    {"term": "YAML", "definition": "Formato de texto para configuração, mais legível que JSON, usado por Kubernetes, GitHub Actions e Ansible."},
    {"term": "HCL", "definition": "HashiCorp Configuration Language: a linguagem usada para escrever arquivo Terraform."},

    # Rede e criptografia (protocolos e conceitos citados nas aulas de fundamentos)
    {"term": "RTT", "definition": "Round-Trip Time: tempo de ida e volta de um pacote entre cliente e servidor, base do custo de latência de um handshake."},
    {"term": "HTTP/2", "definition": "Versão do HTTP com multiplexação de requisições numa única conexão TCP, mas ainda sujeita a head-of-line blocking no nível do TCP."},
    {"term": "HTTP/3", "definition": "Versão do HTTP que roda sobre QUIC (UDP) em vez de TCP, eliminando o head-of-line blocking entre streams."},
    {"term": "WireGuard", "definition": "Protocolo de VPN moderno, mais simples e rápido que IPSec/OpenVPN, com criptografia enxuta e implementação pequena."},
    {"term": "handshake", "definition": "Troca inicial de mensagens entre cliente e servidor para negociar parâmetros (versão, chave, algoritmo) antes do tráfego real começar."},
    {"term": "head-of-line blocking", "definition": "Quando a perda de um pacote trava a entrega de todos os que vêm depois dele, mesmo já tendo chegado ao destino."},
    {"term": "hashing", "definition": "Função que transforma qualquer dado num valor de tamanho fixo (hash); usada para senha, integridade de arquivo e índice."},
    {"term": "post-quantum", "definition": "Algoritmo de criptografia projetado para resistir a um futuro computador quântico capaz de quebrar RSA e curva elíptica."},

    # Ferramentas e plataformas citadas com frequência nas aulas
    {"term": "Kubernetes", "definition": "Orquestrador que gerencia o ciclo de vida de containers em um cluster: agenda, reinicia, escala e distribui carga automaticamente."},
    {"term": "K8s", "definition": "Abreviação numérica de Kubernetes (8 letras entre o K e o s)."},
    {"term": "Docker", "definition": "Ferramenta mais usada para construir, rodar e distribuir containers a partir de uma imagem."},
    {"term": "Docker Compose", "definition": "Ferramenta que sobe múltiplos containers relacionados (app, banco, cache) a partir de um único arquivo YAML declarativo."},
    {"term": "Terraform", "definition": "Ferramenta de Infrastructure as Code que descreve recursos de nuvem em arquivo declarativo e aplica o estado desejado."},
    {"term": "GitHub Actions", "definition": "Plataforma de CI/CD integrada ao GitHub: roda pipeline de build, teste e deploy a partir de eventos no repositório."},
    {"term": "Ansible", "definition": "Ferramenta de automação e configuração de servidor que executa tarefas remotamente via SSH, sem precisar instalar agente."},
    {"term": "Prometheus", "definition": "Sistema de monitoramento que coleta métricas numéricas em série temporal e dispara alerta com base em regra."},
    {"term": "Grafana", "definition": "Ferramenta de visualização que monta dashboard a partir de fontes de dado como Prometheus, Loki e bancos relacionais."},
    {"term": "Loki", "definition": "Sistema de agregação de logs feito para trabalhar junto com Grafana; indexa só metadado (labels), não o conteúdo do log."},
    {"term": "Vault", "definition": "Ferramenta da HashiCorp para guardar e distribuir segredo (senha, chave, certificado) com controle de acesso e rotação."},
    {"term": "Helm", "definition": "Gerenciador de pacotes para Kubernetes: empacota um conjunto de manifests como um chart reutilizável e versionado."},
    {"term": "Ingress", "definition": "Recurso do Kubernetes que expõe serviços internos do cluster para fora via HTTP/HTTPS, com roteamento por host ou path."},
    {"term": "Dockerfile", "definition": "Arquivo de texto com as instruções passo a passo para construir uma imagem de container."},
    {"term": "GitOps", "definition": "Prática de manter o estado desejado da infraestrutura declarado em Git, com uma ferramenta sincronizando o cluster automaticamente."},
    {"term": "Argo CD", "definition": "Ferramenta de GitOps para Kubernetes que sincroniza continuamente o estado do cluster com o que está declarado num repositório Git."},
    {"term": "Falco", "definition": "Ferramenta de detecção de comportamento suspeito em runtime, observando as chamadas de sistema (syscalls) de um container."},
    {"term": "Cilium", "definition": "Plugin de rede (CNI) para Kubernetes baseado em eBPF, com NetworkPolicy avançada e observabilidade de tráfego."},
    {"term": "Istio", "definition": "Service mesh que adiciona mTLS, controle de tráfego e observabilidade entre serviços sem mudar o código da aplicação."},
    {"term": "Linkerd", "definition": "Service mesh mais leve que o Istio, com foco em simplicidade operacional e baixo overhead."},
    {"term": "OPA", "definition": "Open Policy Agent: motor de policy as code que avalia regras (escritas em Rego) contra qualquer tipo de dado estruturado."},
    {"term": "Rego", "definition": "Linguagem de consulta usada pelo OPA para escrever regra de política como código."},
    {"term": "Kyverno", "definition": "Motor de policy as code nativo do Kubernetes, com regras escritas em YAML em vez de Rego."},
    {"term": "Gatekeeper", "definition": "Admission controller que usa OPA para validar ou rejeitar recursos do Kubernetes antes de serem criados."},
    {"term": "Harbor", "definition": "Registry de imagem de container open source, com controle de acesso, scan de vulnerabilidade e replicação nativos."},
    {"term": "Trivy", "definition": "Scanner open source que encontra vulnerabilidade conhecida em imagem de container, dependência e arquivo de configuração."},
    {"term": "Cosign", "definition": "Ferramenta do projeto Sigstore para assinar e verificar a autenticidade de uma imagem de container ou artefato."},
    {"term": "OpenTelemetry", "definition": "Padrão aberto e vendor-neutro para instrumentar aplicações e coletar métrica, log e trace de forma unificada."},
    {"term": "Backstage", "definition": "Portal de desenvolvedor open source, criado pelo Spotify, usado como base de Internal Developer Platforms."},
    {"term": "Datadog", "definition": "Plataforma comercial de observabilidade (métricas, logs, traces e segurança) hospedada como SaaS."},
    {"term": "Cloud Custodian", "definition": "Ferramenta de policy as code para nuvem pública que detecta e corrige automaticamente recurso fora de conformidade."},
    {"term": "Admission Controller", "definition": "Componente do Kubernetes que intercepta uma requisição à API antes dela ser persistida, podendo validar ou modificar o recurso."},
    {"term": "ServiceAccount", "definition": "Identidade usada por um processo (não uma pessoa) para se autenticar contra a API do Kubernetes."},
    {"term": "CloudTrail", "definition": "Serviço da AWS que registra toda chamada feita à API da conta, essencial para auditoria e investigação de incidente."},
    {"term": "PoLP", "definition": "Principle of Least Privilege: conceder a uma identidade só a permissão mínima necessária para fazer seu trabalho."},
    {"term": "Log4Shell", "definition": "Vulnerabilidade crítica de RCE (CVE-2021-44228) na biblioteca Log4j, que acelerou a adoção de SBOM na indústria."},
    {"term": "CycloneDX", "definition": "Formato aberto de SBOM mantido pela OWASP, com foco em segurança de aplicação e cadeia de suprimento de software."},
    {"term": "ELK", "definition": "Stack de logging composta por Elasticsearch (armazenamento e busca), Logstash (ingestão) e Kibana (visualização)."},
    {"term": "TTL", "definition": "Time To Live: por quanto tempo um dado (cache, registro DNS, sessão) permanece válido antes de expirar."},
    {"term": "IPv6", "definition": "Versão mais recente do protocolo IP, com espaço de endereço muito maior que o IPv4, criado para não esgotar endereços."},
]
